base:
  random_seed: 42
data:
  null_handled_data_csv: data/processed/yellow_tripdata_2023-01_null_handled.csv
  processed_data_csv: data/processed/yellow_tripdata_2023-01_processed.csv
  raw_data_csv: data/raw/yellow_tripdata_2023-01.csv
  raw_data_parquet: data/raw/yellow_tripdata_2023-01.parquet
  test_size: 0.2
  train_data_csv: data/processed/train_data.csv
  val_data_csv: data/processed/val_data.csv
eval:
  metrics_file_lgbm: metrics_lgbm.json
  metrics_file_pynn: metrics_pynn.json
  metrics_file_tabnet: metrics_tabnet.json
  metrics_file_xgboost: metrics_xgboost.json
  reports_dir: reports
features:
  categorical:
  - VendorID
  - RatecodeID
  - store_and_fwd_flag
  - payment_type
  - PULocationID
  - DOLocationID
  - time_of_day
  numerical:
  - passenger_count
  - trip_distance
  - fare_amount
  - extra
  - mta_tax
  - tip_amount
  - tolls_amount
  - improvement_surcharge
  - total_amount
  - congestion_surcharge
  - pickup_hour
  - pickup_weekday
  - is_weekend
  - pickup_day
  - month
  - is_peak
reports:
  kde:
    lgbm: reports/KDEPlot_LGBM.jpg
train:
  LReg:
    ElasticNet:
      alpha: 0.1
      l1_ratio: 0.5
      max_iter: 10000
    Lasso:
      alpha: 0.1
      max_iter: 10000
    Ridge:
      alpha: 1.0
  LightGBM:
    device: gpu
    early_stopping_rounds: 20
    learning_rate: 0.05
    min_child_samples: 20
    model_path: models/LightGBM_model.pkl
    n_estimators: 500
    num_leaves: 31
  PyNN:
    batch_size: 1024
    cat_dims:
    - 2
    - 7
    - 2
    - 5
    - 256
    - 261
    - 4
    epochs: 100
    lr: 0.002
    model_path: models/PyNN_model.pt
    num_workers: 0
    patience: 20
    patience_counter: 0
  TabNet:
    batch_size: 1024
    eval_metric:
    - rmse
    max_epochs: 20
    model_path: models/TabNet_model.pkl
    num_workers: 0
    patience: 5
    virtual_batch_size: 128
  XGBoost:
    colsample_bytree: 0.8
    device: cuda
    early_stopping_rounds: 20
    learning_rate: 0.05
    max_depth: 16
    model_path: models/XGBoost_model.pkl
    n_estimators: 500
    objective: reg:squarederror
    random_state: 42
    subsample: 0.8
    tree_method: hist
